name: Example
on:   
  push:
    branches: [main] # add with comma for more branches to monitor
  pull_request:
    branches: [main]

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  # FIREBASE_ADMIN_PASSPHRASE: ${{secrets.FIREBASE_ADMIN_PASSPHRASE}}

jobs:
  example:
    name: Create Ubuntu OS
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.3
          
      - name: Check Go Version
        run: go version

      - name: Checkout Repo   # to pull out current repo code
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: |
          #go mod init calc # for go mod. If we use go build, it will do the same for the 3 lines.
          go mod tidy
          go get github.com/franela/goblin
          ls
      
      # - name: Setup Firebase JSON file
      #   run: echo "{${{ secrets.FIREBASE_JSON }}}" > edusync-7bd5e-firebase-adminsdk-x49uh-af084a6314.json

      # - name: Build and run JSON validator
      #   run: |
      #     go run json_validator.go edusync-7bd5e-firebase-adminsdk-x49uh-af084a6314.json

      - name: Decrypt Firebase JSON
        run: |
          chmod +x decrypt_secret.sh
          ./decrypt_secret.sh
        env:
          FIREBASE_ADMIN_PASSPHRASE: ${{secrets.FIREBASE_ADMIN_PASSPHRASE}}

      - name: Testing, to be removed
        run: |
          ls
          cat edusync-7bd5e-firebase-adminsdk-x49uh-af084a6314.json

      - name: Go Test
        run: |
          go test

      - if: ${{success()}}
        name: Success Message (Discord)
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
          message: SUCCESSFULLLL in branch ${{github.ref}} by ${{github.actor}}

      - if: ${{success()}}
        name: Success Message (Telegram)
        uses: akeylimepie/telegram-action@v0.1.2
        with: 
          token: ${{secrets.TELEGRAM_TOKEN}}
          chat_id: ${{secrets.TELEGRAM_CHAT_ID}}
          text: SUCCESSFULLLL in branch ${{github.ref}} by ${{github.actor}}
          
      - if: ${{failure()}}
        name: Failure Message (Discord)
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
          message: FAILUREEEE in branch ${{github.ref}} by ${{github.actor}}

      - if: ${{failure()}}
        name: Failure Message (Telegram)
        uses: akeylimepie/telegram-action@v0.1.2
        with: 
          token: ${{secrets.TELEGRAM_TOKEN}}
          chat_id: ${{secrets.TELEGRAM_CHAT_ID}}
          text: FAILUREEEE in branch ${{github.ref}} by ${{github.actor}}
      
      #- name: Setup Python
        #uses: actions/setup-python@v5.1.0
        #with:
          #python-version: 3.8
          
      #- name: Show Python Version
        #run: |
          #ls
          #python --version
          #ls
          #pip3 install pandas
    